name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      #Copy to Yandex.Cloud
      - run: cat "$HOME/.ssh/key"
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" . admroot@217.28.231.6:/home/admroot/snake/
